/**
 * The wa-wire boundary, in TypeScript.
 *
 * Its own package rather than part of an adapter, because two adapters need it
 * and they are both TypeScript. The format is written three times across the
 * project — Rust, TypeScript, Go — and three is the number of *languages* an
 * adapter runs in, not the number of adapters. A fourth writing in a language
 * that already has one would be a description nobody checks against the other.
 *
 * Nothing here imports an engine. That is what makes it shareable, and it is
 * also what lets its fixtures be regenerated by anyone without one.
 */
export * from './envelope.js'
export * from './capability.js'
export * from './recording.js'
